### PR TITLE
fix: callback exception should not crash tcp-base

### PR DESCRIPTION
**Pull request by gxcsoccer**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by fengmk2** [comment]
+1

**Comment by fengmk2** [comment]
@gxcsoccer owner 加一下我

**Comment by gxcsoccer** [comment]
\+ fengmk2 (tcp-base)
+ coderhaoxin (tcp-base)

**Comment by fengmk2** [comment]
1.0.1

**Pull request merged**
