### PR TITLE
refactor: [BREAKING-CHANGE] upgrade sdk-base

### PR DESCRIPTION
**Pull request by gxcsoccer**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by gxcsoccer** [comment]
因为 `sdk-base@3` 只支持 node >= 6 所以是 breaking change

**Comment by gxcsoccer** [comment]
不升级的化，很多地方引入两个 sdk-base 版本

**Review by fengmk2 — APPROVED** [review]
是什么原因不支持node4？

**Review by shaoshuai0102 — APPROVED** [review]
LGTM

**Comment by shaoshuai0102** [comment]
自己发吧，我没这个权限

**Comment by gxcsoccer** [comment]
> 是什么原因不支持node4？

@fengmk2 sdk-base@3 不支持 node4 了

**Comment by gxcsoccer** [comment]
\+ shaoshuai0102 (tcp-base)
\+ tcp-base@2.0.0

**Pull request merged**
